Style/ClassAndModuleChildren:
  Enabled: false
Style/GuardClause:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/ClassLength:
  Max: 200
Metrics/ModuleLength:
  Max: 200
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Metrics/MethodLength:
  Max: 40
Metrics/AbcSize:
  Max: 40
Metrics/BlockLength:
  Max: 400
AllCops:
  Exclude:
    - 'lib/chef_backup/deep_merge.rb'
    - 'lib/chef_backup/mash.rb'
    - 'spec/unit/mash_spec.rb'
    - 'spec/unit/deep_merge_spec.rb'
    - 'vendor/**/*'
    - 'Guardfile'
    - 'lib/chef_backup/helpers.rb'
    - 'lib/chef_backup/strategy/backup/tar.rb'
